#!/usr/bin/env python3
"""Extract the countries used by the xkga map scenes from Natural Earth (public domain).

Usage:
  curl -sSL -o /tmp/ne50.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson
  python3 scripts/extract_countries.py /tmp/ne50.geojson src/xkga/data/countries.ts

Output: TS module exporting COUNTRIES = {ISO3: [[ [lon,lat], ... ], ...]}  -- list of rings (outer rings only),
coordinates rounded to 3 decimals, longitudes < -150 shifted +360 so Russia's
Chukotka stays contiguous on an Asia-centred equirectangular map.
"""
import json
import sys

KEEP = ["VNM", "KOR", "JPN", "SGP", "HKG", "RUS", "KHM", "LAO", "MNG"]


def ring(coords):
    out = []
    for lon, lat in coords:
        if lon < -150:
            lon += 360
        out.append([round(lon, 3), round(lat, 3)])
    return out


def main(src, dst):
    data = json.load(open(src))
    res = {}
    for f in data["features"]:
        p = f["properties"]
        code = p.get("ADM0_A3") or p.get("ISO_A3")
        if code not in KEEP:
            continue
        g = f["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        res[code] = [ring(poly[0]) for poly in polys]
    missing = [k for k in KEEP if k not in res]
    if missing:
        print("missing:", missing, file=sys.stderr)
    body = json.dumps(res, separators=(",", ":"))
    with open(dst, "w") as fh:
        fh.write("// Generated by scripts/extract_countries.py from Natural Earth 50m (public domain). Do not edit.\n")
        fh.write("export const COUNTRIES: Record<string, number[][][]> = " + body + ";\n")
    print("wrote", dst, {k: len(v) for k, v in res.items()})


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
