// XkgaVi — assembly of the xkga vertical short (1080x1920, 30 fps) from the 12 rows of
// ra-loi-doc-video-ga-han-quoc_v02.md. Timing comes from ./timeline.ts (generated by
// xkga/build_timeline.py together with public/xkga/voice-mix.wav + music-bed.wav).
// Scenes built elsewhere (MapIntro, MapMarkets, Infographic) are played through a time map
// (row second -> scene second, piecewise linear, holds the last state; never loops).
// Every visible word comes from T / T_INFO / T_ROWS.
import React from "react";
import {
  AbsoluteFill,
  Audio,
  Easing,
  Freeze,
  OffthreadVideo,
  Sequence,
  interpolate,
  staticFile,
  useCurrentFrame,
} from "remotion";
import { C, FONT, HEAD_SHADOW, clamp, pop } from "./common";
import { XkgaMapIntro } from "./MapIntro";
import { XkgaMapMarkets } from "./MapMarkets";
import { XKGA_INFO_START, XkgaInfographic, XkgaInfoCues } from "./infographic";
import { T_INFO } from "./texts-info";
import { T_ROWS } from "./texts-rows";
import { TIMELINE, XkgaRow } from "./timeline";

const FPS = 30;
const FADE = 7; // cross-fade frames: each row (except the first) fades in over the end of the previous one
export const XKGA_VI_FRAMES = TIMELINE.totalFrames;

type Key = [number, number]; // [row second, scene second]
const mapTime = (keys: Key[], t: number) => {
  if (t <= keys[0][0]) return keys[0][1];
  for (let i = 1; i < keys.length; i++) {
    if (t <= keys[i][0]) {
      const [t0, v0] = keys[i - 1];
      const [t1, v1] = keys[i];
      return v0 + ((t - t0) / (t1 - t0)) * (v1 - v0);
    }
  }
  return keys[keys.length - 1][1];
};

// ---------------------------------------------------------------- time maps per scene row
// Infographic: scene seconds are reference seconds (XKGA_INFO_START = first frame).
const N_STEPS = T_INFO.steps.length;
const STEP_ROW5 = N_STEPS === 6 ? [2.6, 3.5, 4.3, 6.3, 7.1, 7.9] : Array.from({ length: N_STEPS }, (_, i) => 2.6 + (i * 5.3) / Math.max(1, N_STEPS - 1));
const ROW5_SRC0 = 48.4;
const INFO_CUES: Partial<XkgaInfoCues> = {
  steps: STEP_ROW5.map((s) => ROW5_SRC0 + s), // tiles pop with the spoken list in row 5
  label: ROW5_SRC0 + 0.3, // block title pops with the start of the row 5 narration
  // Green badge at «100% tiêu chí», ~13.5 s into row 6 (row-6 map: 61.0 + t * 14.5 / duration).
  okBadge: 61.0 + 13.5 * 0.87,
  heatTiles: [64.6, 65.4, 68.5],
};

const sceneKeys = (row: XkgaRow): Key[] => {
  const d = row.duration;
  switch (row.visual) {
    case "mapIntro": // arc -> question list at «hai bộ câu hỏi» -> «5 NĂM» at «năm năm»
      return [[0, 0], [5.3, 4.0], [10.6, 9.2], [d, 12.7]];
    case "mapMarkets":
      return [[0, 0], [d, 12.5]];
    case "info:agencies": // agencies -> date at «tháng 7…» -> inspection bar at «các đoàn…» -> steps label
      return [[0, 37.1], [8.0, 41.2], [8.6, 42.3], [11.2, 44.8], [11.8, 45.5], [16.0, 47.2], [16.6, 47.9], [d, ROW5_SRC0]];
    case "info:grid":
      return [[0, ROW5_SRC0], [d, ROW5_SRC0 + d]];
    case "info:heat":
      return [[0, 61.0], [d, 75.5]];
    default:
      return [[0, 0], [d, d]];
  }
};

const SceneRow: React.FC<{ row: XkgaRow; lead: number }> = ({ row, lead }) => {
  const f = useCurrentFrame();
  const t = Math.max(0, (f - lead) / FPS);
  const s = mapTime(sceneKeys(row), t);
  if (row.visual === "mapIntro") {
    return (
      <Freeze frame={Math.round(s * FPS)}>
        <XkgaMapIntro />
      </Freeze>
    );
  }
  if (row.visual === "mapMarkets") {
    return (
      <Freeze frame={Math.round(s * FPS)}>
        <XkgaMapMarkets />
      </Freeze>
    );
  }
  // Row 4 opens closer on the two agency tiles, then eases back to the full layout as the date tile arrives.
  const zoom = row.visual === "info:agencies" ? interpolate(t, [0, 7.4, 8.4], [1.42, 1.42, 1], { ...clamp, easing: Easing.inOut(Easing.cubic) }) : 1;
  return (
    <AbsoluteFill style={{ transform: `scale(${zoom})`, transformOrigin: "540px 890px" }}>
      <Freeze frame={Math.max(0, Math.round((s - XKGA_INFO_START) * FPS))}>
        <XkgaInfographic cues={INFO_CUES} okBadgeY={2950} />
      </Freeze>
    </AbsoluteFill>
  );
};

// ---------------------------------------------------------------- overlays
const AiLabel: React.FC = () => (
  <div
    style={{
      position: "absolute",
      top: 70,
      right: 44,
      padding: "8px 16px",
      borderRadius: 10,
      background: "rgba(0,0,0,0.5)",
      color: "rgba(255,255,255,0.88)",
      fontFamily: FONT,
      fontWeight: 600,
      fontSize: 24,
      letterSpacing: 0.5,
    }}
  >
    {T_ROWS.aiLabel}
  </div>
);

/** Big stacked headline over b-roll: orange italic / white alternating, dark band behind. */
const HeadlineOverlay: React.FC<{ lines: string[]; lead: number }> = ({ lines, lead }) => {
  const f = useCurrentFrame();
  const bandIn = interpolate(f, [lead, lead + 10], [0, 1], clamp);
  const sizeOf = (s: string) => Math.min(112, Math.floor(900 / (Array.from(s).length * 0.66)));
  return (
    <AbsoluteFill>
      <AbsoluteFill
        style={{
          opacity: bandIn,
          background:
            "linear-gradient(to bottom, rgba(0,0,0,0) 22%, rgba(0,0,0,0.72) 36%, rgba(0,0,0,0.72) 60%, rgba(0,0,0,0) 76%)",
        }}
      />
      <div
        style={{
          position: "absolute",
          left: 40,
          right: 40,
          top: 0,
          bottom: 0,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          paddingBottom: 140,
          fontFamily: FONT,
          fontWeight: 900,
          textAlign: "center",
        }}
      >
        {lines.map((l, i) => {
          const p = pop(f, lead + 6 + i * 7);
          const orange = i % 2 === 0;
          return (
            <div
              key={i}
              style={{
                fontSize: sizeOf(l),
                lineHeight: 1.08,
                color: orange ? C.orange : C.white,
                fontStyle: orange ? "italic" : "normal",
                textShadow: HEAD_SHADOW,
                letterSpacing: -0.5,
                whiteSpace: "nowrap",
                opacity: Math.min(1, p * 1.6),
                transform: `scale(${0.8 + 0.2 * p})`,
              }}
            >
              {l}
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

/** Lower-left boxed caption (reference presenter style): chunks shown two per screen, equal time per chunk. */
const PresenterCaption: React.FC<{ chunks: string[]; lead: number; frames: number }> = ({ chunks, lead, frames }) => {
  const f = useCurrentFrame() - lead;
  if (f < 0 || chunks.length === 0) return null;
  const groups: string[][] = [];
  for (let i = 0; i < chunks.length; i += 2) groups.push(chunks.slice(i, i + 2));
  const per = frames / chunks.length;
  let acc = 0;
  let gi = 0;
  let gStart = 0;
  for (let i = 0; i < groups.length; i++) {
    const len = groups[i].length * per;
    if (f < acc + len || i === groups.length - 1) {
      gi = i;
      gStart = acc;
      break;
    }
    acc += len;
  }
  const local = f - gStart;
  const inP = interpolate(local, [0, 5], [0, 1], clamp);
  return (
    <div
      style={{
        position: "absolute",
        left: 70,
        top: 1150,
        maxWidth: 900,
        display: "flex",
        alignItems: "stretch",
        background: "rgba(0,0,0,0.42)",
        borderRadius: 8,
        padding: "16px 26px 16px 0",
      }}
    >
      <div style={{ width: 10, background: C.orangeHot, borderRadius: 2, marginRight: 24 }} />
      <div
        style={{
          fontFamily: FONT,
          fontWeight: 700,
          fontSize: Math.min(50, ...groups[gi].map((c) => Math.floor(820 / (Array.from(c).length * 0.52)))),
          lineHeight: 1.22,
          color: C.white,
          textShadow: "0 2px 8px rgba(0,0,0,0.8)",
          opacity: inP,
          transform: `translateY(${(1 - inP) * 10}px)`,
        }}
      >
        {groups[gi].map((c, i) => (
          <div key={i}>{c}</div>
        ))}
      </div>
    </div>
  );
};

// ---------------------------------------------------------------- rows
const clipsOf = (row: XkgaRow) => row.visual.split(":")[1].split(",");

const BrollRow: React.FC<{ row: XkgaRow; lead: number }> = ({ row, lead }) => {
  const clips = clipsOf(row);
  const total = lead + row.durationFrames;
  const half = Math.ceil(total / clips.length);
  return (
    <AbsoluteFill style={{ background: "#000" }}>
      {clips.map((c, i) => {
        const from = i * half;
        const len = i === clips.length - 1 ? total - from : half + FADE;
        const rate = Math.min(1, (5.9 * FPS) / len); // stretch a 6 s clip if its slot is longer
        return (
          <Sequence key={i} from={from} durationInFrames={len}>
            <ClipFade first={i === 0} fadeIn={FADE}>
              <OffthreadVideo src={staticFile(`xkga/media/${c}`)} muted playbackRate={rate} style={{ width: "100%", height: "100%", objectFit: "cover" }} />
            </ClipFade>
          </Sequence>
        );
      })}
      <HeadlineOverlay lines={T_ROWS.overlay[row.row] ?? []} lead={lead} />
      <AiLabel />
    </AbsoluteFill>
  );
};

const ClipFade: React.FC<{ first: boolean; fadeIn: number; children: React.ReactNode }> = ({ first, fadeIn, children }) => {
  const f = useCurrentFrame();
  const o = first ? 1 : interpolate(f, [0, fadeIn], [0, 1], clamp);
  return <AbsoluteFill style={{ opacity: o }}>{children}</AbsoluteFill>;
};

const PresenterRow: React.FC<{ row: XkgaRow; lead: number }> = ({ row, lead }) => {
  const f = useCurrentFrame();
  const src = staticFile(`xkga/media/${clipsOf(row)[0]}`);
  const style: React.CSSProperties = { width: "100%", height: "100%", objectFit: "cover" };
  return (
    <AbsoluteFill style={{ background: "#000" }}>
      {f < lead ? (
        <Freeze frame={0}>
          <OffthreadVideo src={src} muted style={style} />
        </Freeze>
      ) : (
        <Sequence from={lead} durationInFrames={row.durationFrames}>
          <OffthreadVideo src={src} muted style={style} />
        </Sequence>
      )}
      <PresenterCaption chunks={T_ROWS.captions[row.row] ?? []} lead={lead} frames={row.durationFrames} />
      <AiLabel />
    </AbsoluteFill>
  );
};

const RowView: React.FC<{ row: XkgaRow; lead: number }> = ({ row, lead }) => {
  const f = useCurrentFrame();
  const opacity = lead > 0 ? interpolate(f, [0, lead], [0, 1], clamp) : 1;
  const kind = row.visual.split(":")[0];
  return (
    <AbsoluteFill style={{ opacity }}>
      {kind === "omni" ? (
        <BrollRow row={row} lead={lead} />
      ) : kind === "presenter" ? (
        <PresenterRow row={row} lead={lead} />
      ) : (
        <SceneRow row={row} lead={lead} />
      )}
    </AbsoluteFill>
  );
};

export const XkgaVi: React.FC = () => (
  <AbsoluteFill style={{ background: "#000", fontFamily: FONT }}>
    {TIMELINE.rows.map((row, i) => {
      const lead = i === 0 ? 0 : FADE;
      return (
        <Sequence key={row.row} from={row.startFrame - lead} durationInFrames={row.durationFrames + lead} name={`row ${row.row}`}>
          <RowView row={row} lead={lead} />
        </Sequence>
      );
    })}
    <Audio src={staticFile("xkga/voice-mix.wav")} />
    <Audio src={staticFile("xkga/music-bed.wav")} />
  </AbsoluteFill>
);
